def image

pipeline {
    agent { 
        label 'master'
        }
    triggers { pollSCM('*/15 * * * *') }
    options {
        timestamps()
    }
    stages {
        stage("docker build") {
            steps {
                script {
                    dir("${pwd()}/application") {
                        //pylint???
                        //docker.withRegistry('https://registry.hub.docker.com','docker_hub_alexv77745') {                            
                            //def image = docker.build("alexv77745/diploma:${env.GIT_BRANCH}-${env.BUILD_ID}")
                            def sha = env.GIT_COMMIT.substring(0,8)
                            image = docker.build("alexv77745/diploma:${env.GIT_BRANCH}-${sha}")
                        }
                    }
                }
            }
        }    
        stage("docker push") {
            steps {
                script {
                    dir("${pwd()}/application") {
                        //pylint???
                        docker.withRegistry('https://registry.hub.docker.com','docker_hub_alexv77745') {                      
                            image.push()
                            image.push('latest')
                        }
                    }
                }
            }
        }    
    }
}    
