def image

pipeline {
    agent { 
        label 'master'
        }
    triggers { pollSCM('*/15 * * * *') }
    options {
        timestamps()
    }
    stages {
        stage("pylint revision") {
            steps {
                sh 'pylint  --disable=missing-docstring  application/diploma_app.py'
            }
        }    
        stage("docker build") {
            steps {
                script {
                    dir("${pwd()}/application") {
                        docker.withRegistry('https://registry.hub.docker.com','docker_hub_alexv77745') {                            
                            def sha = env.GIT_COMMIT.substring(0,8)
                            image = docker.build("alexv77745/diploma:${env.GIT_BRANCH}-${sha}")
                        }
                    }
                }
            }
        }    
        stage("docker push") {
            steps {
                script {                      
                    image.push()
                    image.push('latest')
                }
            }
        }    
    }
}    
